import requests
import json
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Get the API key from the environment variables
api_key_external = os.getenv("API_KEY_EXTERNAL")

# Read the 'slug' from the JSON file generated by get-user-by-email.py
json_filename = os.path.join(os.path.dirname(__file__), 'output.json')

with open(json_filename, 'r') as json_file:
    data = json.load(json_file)
    slug = data.get('slug', '')

# Construct the API URL using the 'slug'
api_url_external = f"https://api.cr4ce.com/user/{slug}/auth-token"

# Print the constructed URL with the slug
print(f"Constructed URL: {api_url_external}")

# Define the headers
headers = {
    'Accept': 'application/vnd.Creative Force.v2.1+json',
    'x-api-key': api_key_external
}

# Send the GET request
response = requests.get(api_url_external, headers=headers)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Print the authentication token in the terminal
    print(f"Authentication Token: {data['auth_token']}")

    # Save the authentication token to a JSON file
    auth_token_filename = os.path.join(os.path.dirname(__file__), 'auth_token.json')
    with open(auth_token_filename, 'w') as auth_token_file:
        json.dump(data, auth_token_file, indent=4)

    print(f"Authentication Token has been saved to {auth_token_filename}")
else:
    print(f"Request failed with status code: {response.status_code}")
    print(response.text)  # Print the response content if there's an error
